version: 0.2

phases:
  pre_build:
    commands:
      - service postgresql start 
      - su - postgres -c "psql -c \"CREATE USER test_db_dev WITH PASSWORD 'test_db_dev'; ALTER ROLE test_db_dev WITH CREATEDB;\""
      - . /vaultenv/.env/bin/activate
  build:
    commands:
      - cd django && PYTHONPATH=. python runtests.py

  post_build:
    commands:
      - coverage xml

artifacts:
  files:
    - nosetests.xml
  discard-paths: yes
  base-directory: django